import Head from "next/head";
import Image from "next/image";
import Link from "next/link";

export default function StarWarsPersonagem() {
  return (
    <div className="">
      <Head>
        <title>Personagem - Star Wars</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="border-t-2 border-blue-200">hello duds</main>

      <footer className=""></footer>
    </div>
  );
}
