import Head from "next/head";
import Image from "next/image";
import Link from "next/link";

export default function Dnd() {
  return (
    <div className="">
      <Head>
        <title>D&D</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="border-t-2 border-blue-200">
        <h1 className="font-sans text-2xl py-4">Meus Homebrews</h1>
        <div className="flex flex-col text-left space-y-4 w-4/5 mx-auto md:w-3/5 xl:w-2/5">
          <div className="flex-1 border-blue-200 border-2 px-4 space-y-2 py-4 rounded hover:border-blue-300 transform hover:scale-105 transition-transform">
            <h1 className="text-xl text-blue-600">Velocista</h1>
            <h2 className="text-sm text-gray-700">Arquétipo de Monge</h2>
            <p className="">
              Proin nec sodales nibh. Vivamus at nibh vitae ex mollis lobortis
              id eget mauris. Sed semper orci vel nibh aliquet elementum. Sed et
              velit sed turpis dignissim vulputate. Nullam feugiat condimentum
              tellus, id fringilla lacus cursus non. Sed id sagittis ipsum.
              Integer vel arcu libero.
            </p>

            <Link href="">
              <a className="">
                <button>Ver</button>
              </a>
            </Link>
          </div>

          <div className="flex-1 border-blue-200 border-2 px-4 space-y-2 py-4 rounded hover:border-blue-300 transform hover:scale-105 transition-transform">
            <h1 className="text-xl text-blue-600">Hoplita</h1>
            <h2 className="text-sm text-gray-700">Arquétipo de Guerreiro</h2>
            <p className="">
              Proin nec sodales nibh. Vivamus at nibh vitae ex mollis lobortis
              id eget mauris. Sed semper orci vel nibh aliquet elementum. Sed et
              velit sed turpis dignissim vulputate. Nullam feugiat condimentum
              tellus, id fringilla lacus cursus non. Sed id sagittis ipsum.
              Integer vel arcu libero.
            </p>
            <Link href="">
              <a className="">
                <button>Ver</button>
              </a>
            </Link>
          </div>
        </div>
      </main>

      <footer className=""></footer>
    </div>
  );
}
