import Head from "next/head";
import Image from "next/image";
import Link from "next/link";

export default function Home() {
  return (
    <div className="">
      <Head>
        <title>RPG da Discórdia</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h1 className="text-xl">Aqui é onde tudo começa</h1>
        <p>Você encontra adaptações de sistemas de RPG e conteúdos homebrew para D&D 5E, todos feitos por mim.</p>
        </main>

      <footer className=""></footer>
    </div>
  );
}
