import Head from "next/head";
import Image from "next/image";
import Link from "next/link";

export default function StarWars() {
  return (
    <div className="">
      <Head>
        <title>Star Wars</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="border-t-2 border-blue-200">
        <div className="flex flex-row py-4 space-x-4 md:text-sm">
          <div><Link href=""><a><button>Regras Básicas</button></a></Link></div>
          <div><Link href=""><a><button>Personagem</button></a></Link></div>
          <div><Link href=""><a><button>A Força</button></a></Link></div>
          <div><Link href=""><a><button>Equipamentos</button></a></Link></div>
          <div><Link href=""><a><button>Testes & Combate</button></a></Link></div>
          <div><Link href=""><a><button>Veículos</button></a></Link></div>
          <div><Link href=""><a><button>Duelo</button></a></Link></div>
        </div>
      </main>

      <footer className=""></footer>
    </div>
  );
}
